### PR TITLE
deprecated old relation syntax: fixes #2000

### LINKED ISSUE #2000: Deprecate the old relation syntax
The new relation syntax was introduced more than 3 years ago. We should start printing deprecation warnings so that any old syntax can be found and fixed.

### PR DESCRIPTION
**Pull request by sanderr**
# Description

Deprecated the old relation definition syntax.

closes #2000

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

### CODE REVIEW

**Comment by sanderr** [comment]
At this point these changes cause some other warning related tests to fail. These tests assert that a single warning is raised for a given model. However, they make use of std, and std makes use of the old relation syntax. I believe this should be fixed, but I'm not sure if changes should be made to this pull request. Do I just apply the new syntax in std, and block this pull request until the std one is merged?

**Comment by bartv** [comment]
@wouterdb update the vendored std?

**Comment by wouterdb** [comment]
@bart: the actual std is the problem ;-)

@sanderr : please go ahead and update std.

**Comment by sanderr** [comment]
The tests still fail because their `install_mode` is not `master` (`tests/conftest.py:SnippetCompilationTest.setup_for_snippet_external`). I assume this should not change. How then do we make sure these tests start succeeding?

**Comment by wouterdb** [comment]
I released std, so that should fix it

**Pull request merged**
