### PR TITLE
Don't wait for already terminated processes

### PR DESCRIPTION
**Pull request by andraskvr**
Related to #1098 
It seems that the wait_for_exit waits for the timeout when the process has already ended.
This affects the runtime of tests/test_server.py::test_autostart and tests/test_server.py::test_autostart_batched for example (locally it reduced the total runtime by ~30 sec)

### CODE REVIEW

**Comment by andraskvr** [comment]
Also about these tests:
The agent is started, killed, started again and then the second agent is started, and it's expected that only 1 session is active after that. 
The question is, that is it necessary to kill and start the first agent again to properly test what it was meant to?
And if it is, is it necessary in both test cases?
https://github.com/inmanta/inmanta/blob/53b8bc32cf4a7c013afbda5eb84feeecdca7f7d5/tests/test_server.py#L66
https://github.com/inmanta/inmanta/blob/53b8bc32cf4a7c013afbda5eb84feeecdca7f7d5/tests/test_server.py#L157
@wouterdb ?

**Comment by wouterdb** [comment]
test_autostart and test_autostart_dual_env can be merged into one

test_autostart_batched may still be usefull, but it could perhaps be optimized by mocking out some of the slower parts.

**Comment by andraskvr** [comment]
Sorry I wasn't clear, I meant that I don't really understand the flow in test_autostart: 

Is it necessary to kill the first agent and restart it, only for it to be killed again when the second agent starts?

**Comment by wouterdb** [comment]
good point. I think the original intent was to 
1-ensure it recovers after unexpected failure (first kill)
2-ensure it correctly handles restart for controlled termination 

both cases have different flow iirc (the controlled case should be faster due to optimizations in connection termination iirc)

**Pull request merged**
