### PR TITLE
made attribute location a range

### PR DESCRIPTION
**Pull request by sanderr**
# Description

This PR makes `Attribute` location a `Range` instead of a plain `Location`. This is related to #2481 though while working on this I realized the handling of plain `Location` instances can be improved on the vscode side as well. Now I'm not sure this PR should even be merged. The question is what we want the `Attribute`'s location to represent:
- just a line number, as it is now (don't merge this PR (or change it a bit, there's an inconsistency in the tokens used for the location of dicts and other attributes respectively))
- the range of the type declaration
- the range of the attribute name (current status of this PR)
- the combined range of the type declaration and the attribute name (without leading whitespace)

@wouterdb @arnaudsjs wdyt? I'm slightly in favor of leaving this as is (except for the dict-related changes mentioned above).

Some tests are failing because of these changes. I'll fix those once a decision has been reached.

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] ~~Attached issue to pull request~~
- [ ] Changelog entry
- [x] ~~Type annotations are present~~
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [x] Correct, in line with design
- [x] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

### CODE REVIEW

**Review by wouterdb — COMMENTED** [review]
I also have no strong preference.

- I prefer ranges to lines (more precise)
- I would not just take the type (bit weird, no?)
- I don't know if we need to take the entire declaration or just the identifier.

**Comment by sanderr** [comment]
If using a `Range` my preference would be to use the identifier. The entire declaration would be an option as well but in theory that could span multiple lines. I agree just using the type would be weird, I just wanted to include all plausible options.

**Comment by arnaudsjs** [comment]
I agree to take the range of the identifier.

**Comment by sanderr** [comment]
closes #2481

**Review by wouterdb — APPROVED** [review]

**Review by arnaudsjs — APPROVED** [review]

**Pull request merged**
